"""
core/constants.py
─────────────────
Static mappings: rating strings → numeric scores, GICS sector classification.
"""

# ── Analyst rating → numeric score ──────────────────────────────────────────
RATING_SCORE_MAP: dict[str, float] = {
    "strong buy": 5.0,
    "strong_buy": 5.0,
    "strongbuy": 5.0,
    "top pick": 5.0,
    "conviction buy": 5.0,
    "buy": 4.0,
    "outperform": 4.0,
    "overweight": 4.0,
    "accumulate": 4.0,
    "market outperform": 4.0,
    "sector outperform": 4.0,
    "add": 4.0,
    "hold": 3.0,
    "neutral": 3.0,
    "market perform": 3.0,
    "sector perform": 3.0,
    "equal weight": 3.0,
    "in-line": 3.0,
    "inline": 3.0,
    "peer perform": 3.0,
    "sell": 2.0,
    "underperform": 2.0,
    "underweight": 2.0,
    "reduce": 2.0,
    "market underperform": 2.0,
    "sector underperform": 2.0,
    "strong sell": 1.0,
    "strong_sell": 1.0,
    "strongsell": 1.0,
    "conviction sell": 1.0,
}

# ── GICS sector classification ───────────────────────────────────────────────
TICKER_INDUSTRY_MAP: dict[str, str] = {

    # ── Information Technology ───────────────────────────────────────────
    "AAPL":  "Information Technology",
    "MSFT":  "Information Technology",
    "NVDA":  "Information Technology",
    "AVGO":  "Information Technology",
    "AMD":   "Information Technology",
    "ORCL":  "Information Technology",
    "CRM":   "Information Technology",
    "ADBE":  "Information Technology",
    "QCOM":  "Information Technology",
    "TXN":   "Information Technology",
    "INTC":  "Information Technology",
    "IBM":   "Information Technology",
    "NOW":   "Information Technology",
    "INTU":  "Information Technology",
    "PANW":  "Information Technology",
    "CRWD":  "Information Technology",
    "FTNT":  "Information Technology",
    "AMAT":  "Information Technology",
    "LRCX":  "Information Technology",
    "KLAC":  "Information Technology",
    "MU":    "Information Technology",
    "SNPS":  "Information Technology",
    "CDNS":  "Information Technology",
    "PLTR":  "Information Technology",
    "SNOW":  "Information Technology",
    "ANSS":  "Information Technology",
    "ZBRA":  "Information Technology",
    "CTSH":  "Information Technology",
    "HPQ":   "Information Technology",
    "DELL":  "Information Technology",
    "WDC":   "Information Technology",
    "STX":   "Information Technology",
    "HPE":   "Information Technology",
    "GLW":   "Information Technology",
    "KEYS":  "Information Technology",
    "TRMB":  "Information Technology",
    "TDY":   "Information Technology",
    "GDDY":  "Information Technology",
    "FFIV":  "Information Technology",
    "JNPR":  "Information Technology",
    "NTAP":  "Information Technology",
    "PTC":   "Information Technology",
    "AKAM":  "Information Technology",
    "EPAM":  "Information Technology",
    "IT":    "Information Technology",
    "GEN":   "Information Technology",
    "CTXS":  "Information Technology",
    "TYL":   "Information Technology",
    "PAYC":  "Information Technology",
    "VRSN":  "Information Technology",

    # ── Communication Services ───────────────────────────────────────────
    "GOOGL": "Communication Services",
    "META":  "Communication Services",
    "NFLX":  "Communication Services",
    "DIS":   "Communication Services",
    "T":     "Communication Services",
    "VZ":    "Communication Services",
    "SNAP":  "Communication Services",
    "PINS":  "Communication Services",
    "RDDT":  "Communication Services",
    "SPOT":  "Communication Services",
    "MTCH":  "Communication Services",
    "WBD":   "Communication Services",
    "PARA":  "Communication Services",
    "FOXA":  "Communication Services",
    "NWSA":  "Communication Services",
    "OMC":   "Communication Services",
    "IPG":   "Communication Services",
    "LYV":   "Communication Services",
    "TMUS":  "Communication Services",
    "CHTR":  "Communication Services",
    "LUMN":  "Communication Services",

    # ── Consumer Discretionary ───────────────────────────────────────────
    "AMZN":  "Consumer Discretionary",
    "TSLA":  "Consumer Discretionary",
    "HD":    "Consumer Discretionary",
    "MCD":   "Consumer Discretionary",
    "NKE":   "Consumer Discretionary",
    "SBUX":  "Consumer Discretionary",
    "TGT":   "Consumer Discretionary",
    "LOW":   "Consumer Discretionary",
    "TJX":   "Consumer Discretionary",
    "BKNG":  "Consumer Discretionary",
    "MAR":   "Consumer Discretionary",
    "HLT":   "Consumer Discretionary",
    "RCL":   "Consumer Discretionary",
    "CCL":   "Consumer Discretionary",
    "LVS":   "Consumer Discretionary",
    "MGM":   "Consumer Discretionary",
    "WYNN":  "Consumer Discretionary",
    "F":     "Consumer Discretionary",
    "GM":    "Consumer Discretionary",
    "EBAY":  "Consumer Discretionary",
    "ETSY":  "Consumer Discretionary",
    "ABNB":  "Consumer Discretionary",
    "DASH":  "Consumer Discretionary",
    "ORLY":  "Consumer Discretionary",
    "AZO":   "Consumer Discretionary",
    "BBY":   "Consumer Discretionary",
    "DG":    "Consumer Discretionary",
    "DLTR":  "Consumer Discretionary",
    "ROST":  "Consumer Discretionary",
    "GPC":   "Consumer Discretionary",
    "PHM":   "Consumer Discretionary",
    "DHI":   "Consumer Discretionary",
    "LEN":   "Consumer Discretionary",
    "NVR":   "Consumer Discretionary",
    "TOL":   "Consumer Discretionary",
    "YUM":   "Consumer Discretionary",
    "CMG":   "Consumer Discretionary",
    "DRI":   "Consumer Discretionary",
    "HAS":   "Consumer Discretionary",
    "MAT":   "Consumer Discretionary",
    "RL":    "Consumer Discretionary",
    "TPR":   "Consumer Discretionary",
    "PVH":   "Consumer Discretionary",
    "VFC":   "Consumer Discretionary",
    "EXPE":  "Consumer Discretionary",
    "TRIP":  "Consumer Discretionary",
    "H":     "Consumer Discretionary",
    "HGV":   "Consumer Discretionary",
    "CZR":   "Consumer Discretionary",

    # ── Consumer Staples ─────────────────────────────────────────────────
    "PG":    "Consumer Staples",
    "KO":    "Consumer Staples",
    "PEP":   "Consumer Staples",
    "WMT":   "Consumer Staples",
    "COST":  "Consumer Staples",
    "MO":    "Consumer Staples",
    "PM":    "Consumer Staples",
    "STZ":   "Consumer Staples",
    "MDLZ":  "Consumer Staples",
    "GIS":   "Consumer Staples",
    "K":     "Consumer Staples",
    "HSY":   "Consumer Staples",
    "CPB":   "Consumer Staples",
    "CAG":   "Consumer Staples",
    "HRL":   "Consumer Staples",
    "TSN":   "Consumer Staples",
    "SJM":   "Consumer Staples",
    "MKC":   "Consumer Staples",
    "CLX":   "Consumer Staples",
    "CHD":   "Consumer Staples",
    "CL":    "Consumer Staples",
    "KMB":   "Consumer Staples",
    "EL":    "Consumer Staples",
    "KVUE":  "Consumer Staples",
    "BG":    "Consumer Staples",
    "ADM":   "Consumer Staples",
    "TAP":   "Consumer Staples",
    "BUD":   "Consumer Staples",
    "KR":    "Consumer Staples",
    "SYY":   "Consumer Staples",
    "USFD":  "Consumer Staples",

    # ── Financials ───────────────────────────────────────────────────────
    "JPM":   "Financials",
    "BAC":   "Financials",
    "WFC":   "Financials",
    "GS":    "Financials",
    "MS":    "Financials",
    "BLK":   "Financials",
    "V":     "Financials",
    "MA":    "Financials",
    "C":     "Financials",
    "USB":   "Financials",
    "PNC":   "Financials",
    "TFC":   "Financials",
    "COF":   "Financials",
    "AXP":   "Financials",
    "DFS":   "Financials",
    "SYF":   "Financials",
    "ALLY":  "Financials",
    "SCHW":  "Financials",
    "RJF":   "Financials",
    "AIG":   "Financials",
    "MET":   "Financials",
    "PRU":   "Financials",
    "AFL":   "Financials",
    "ALL":   "Financials",
    "PGR":   "Financials",
    "CB":    "Financials",
    "MMC":   "Financials",
    "AON":   "Financials",
    "MKL":   "Financials",
    "WRB":   "Financials",
    "HIG":   "Financials",
    "CNA":   "Financials",
    "L":     "Financials",
    "FNF":   "Financials",
    "BK":    "Financials",
    "STT":   "Financials",
    "NTRS":  "Financials",
    "RF":    "Financials",
    "CFG":   "Financials",
    "FITB":  "Financials",
    "HBAN":  "Financials",
    "KEY":   "Financials",
    "MTB":   "Financials",
    "WAL":   "Financials",
    "SIVB":  "Financials",
    "LPLA":  "Financials",
    "ICE":   "Financials",
    "CME":   "Financials",
    "CBOE":  "Financials",
    "NDAQ":  "Financials",
    "MSCI":  "Financials",
    "SPGI":  "Financials",
    "MCO":   "Financials",
    "FDS":   "Financials",

    # ── Health Care ──────────────────────────────────────────────────────
    "JNJ":   "Health Care",
    "UNH":   "Health Care",
    "LLY":   "Health Care",
    "ABBV":  "Health Care",
    "MRK":   "Health Care",
    "PFE":   "Health Care",
    "TMO":   "Health Care",
    "ABT":   "Health Care",
    "DHR":   "Health Care",
    "BMY":   "Health Care",
    "AMGN":  "Health Care",
    "GILD":  "Health Care",
    "BIIB":  "Health Care",
    "REGN":  "Health Care",
    "VRTX":  "Health Care",
    "MRNA":  "Health Care",
    "ISRG":  "Health Care",
    "SYK":   "Health Care",
    "BSX":   "Health Care",
    "MDT":   "Health Care",
    "EW":    "Health Care",
    "ZBH":   "Health Care",
    "BDX":   "Health Care",
    "BAX":   "Health Care",
    "HOLX":  "Health Care",
    "DXCM":  "Health Care",
    "ALGN":  "Health Care",
    "IDXX":  "Health Care",
    "IQV":   "Health Care",
    "CRL":   "Health Care",
    "CVS":   "Health Care",
    "CI":    "Health Care",
    "HUM":   "Health Care",
    "CNC":   "Health Care",
    "MOH":   "Health Care",
    "MCK":   "Health Care",
    "CAH":   "Health Care",
    "ABC":   "Health Care",
    "HCA":   "Health Care",
    "THC":   "Health Care",
    "UHS":   "Health Care",
    "DGX":   "Health Care",
    "LH":    "Health Care",

    # ── Energy ───────────────────────────────────────────────────────────
    "XOM":   "Energy",
    "CVX":   "Energy",
    "COP":   "Energy",
    "SLB":   "Energy",
    "EOG":   "Energy",
    "OXY":   "Energy",
    "PSX":   "Energy",
    "VLO":   "Energy",
    "MPC":   "Energy",
    "HES":   "Energy",
    "DVN":   "Energy",
    "FANG":  "Energy",
    "APA":   "Energy",
    "HAL":   "Energy",
    "BKR":   "Energy",
    "MRO":   "Energy",
    "PXD":   "Energy",
    "CTRA":  "Energy",
    "OKE":   "Energy",
    "WMB":   "Energy",
    "KMI":   "Energy",
    "LNG":   "Energy",
    "TRGP":  "Energy",
    "ET":    "Energy",

    # ── Industrials ──────────────────────────────────────────────────────
    "BA":    "Industrials",
    "CAT":   "Industrials",
    "GE":    "Industrials",
    "HON":   "Industrials",
    "UPS":   "Industrials",
    "RTX":   "Industrials",
    "LMT":   "Industrials",
    "NOC":   "Industrials",
    "GD":    "Industrials",
    "LHX":   "Industrials",
    "TDG":   "Industrials",
    "MMM":   "Industrials",
    "EMR":   "Industrials",
    "ETN":   "Industrials",
    "PH":    "Industrials",
    "ROK":   "Industrials",
    "IR":    "Industrials",
    "XYL":   "Industrials",
    "GNRC":  "Industrials",
    "FDX":   "Industrials",
    "JBHT":  "Industrials",
    "CSX":   "Industrials",
    "NSC":   "Industrials",
    "UNP":   "Industrials",
    "DAL":   "Industrials",
    "UAL":   "Industrials",
    "AAL":   "Industrials",
    "LUV":   "Industrials",
    "ALK":   "Industrials",
    "CHRW":  "Industrials",
    "EXPD":  "Industrials",
    "GWW":   "Industrials",
    "FAST":  "Industrials",
    "SNA":   "Industrials",
    "ITW":   "Industrials",
    "DOV":   "Industrials",
    "FTV":   "Industrials",
    "CARR":  "Industrials",
    "OTIS":  "Industrials",
    "PWR":   "Industrials",
    "PCAR":  "Industrials",
    "CMI":   "Industrials",
    "DE":    "Industrials",
    "AGCO":  "Industrials",
    "WM":    "Industrials",
    "RSG":   "Industrials",
    "CTAS":  "Industrials",
    "RHI":   "Industrials",
    "MAN":   "Industrials",

    # ── Real Estate ──────────────────────────────────────────────────────
    "AMT":   "Real Estate",
    "PLD":   "Real Estate",
    "SPG":   "Real Estate",
    "EQIX":  "Real Estate",
    "DLR":   "Real Estate",
    "PSA":   "Real Estate",
    "EXR":   "Real Estate",
    "AVB":   "Real Estate",
    "EQR":   "Real Estate",
    "MAA":   "Real Estate",
    "UDR":   "Real Estate",
    "O":     "Real Estate",
    "WPC":   "Real Estate",
    "NNN":   "Real Estate",
    "VICI":  "Real Estate",
    "GLPI":  "Real Estate",
    "CCI":   "Real Estate",
    "SBAC":  "Real Estate",
    "ARE":   "Real Estate",
    "BXP":   "Real Estate",
    "KIM":   "Real Estate",
    "REG":   "Real Estate",
    "FRT":   "Real Estate",
    "HST":   "Real Estate",
    "PEB":   "Real Estate",
    "CBRE":  "Real Estate",
    "JLL":   "Real Estate",

    # ── Utilities ────────────────────────────────────────────────────────
    "NEE":   "Utilities",
    "DUK":   "Utilities",
    "SO":    "Utilities",
    "AEP":   "Utilities",
    "EXC":   "Utilities",
    "SRE":   "Utilities",
    "PCG":   "Utilities",
    "ED":    "Utilities",
    "XEL":   "Utilities",
    "ES":    "Utilities",
    "AWK":   "Utilities",
    "WEC":   "Utilities",
    "CMS":   "Utilities",
    "DTE":   "Utilities",
    "AES":   "Utilities",
    "ETR":   "Utilities",
    "PPL":   "Utilities",
    "PNW":   "Utilities",
    "NI":    "Utilities",
    "CNP":   "Utilities",
    "EIX":   "Utilities",
    "FE":    "Utilities",
    "ATO":   "Utilities",
    "LNT":   "Utilities",

    # ── Materials ────────────────────────────────────────────────────────
    "LIN":   "Materials",
    "APD":   "Materials",
    "FCX":   "Materials",
    "NEM":   "Materials",
    "GOLD":  "Materials",
    "AA":    "Materials",
    "NUE":   "Materials",
    "STLD":  "Materials",
    "RS":    "Materials",
    "VMC":   "Materials",
    "MLM":   "Materials",
    "ECL":   "Materials",
    "PPG":   "Materials",
    "SHW":   "Materials",
    "RPM":   "Materials",
    "EMN":   "Materials",
    "CE":    "Materials",
    "DOW":   "Materials",
    "LYB":   "Materials",
    "DD":    "Materials",
    "ALB":   "Materials",
    "IFF":   "Materials",
    "MOS":   "Materials",
    "CF":    "Materials",
    "FMC":   "Materials",
    "IP":    "Materials",
    "PKG":   "Materials",
    "SEE":   "Materials",
    "BALL":  "Materials",
    "AMCR":  "Materials",

}

DEFAULT_INDUSTRY = "Unknown"


def get_industry(ticker: str) -> str:
    """Return the GICS sector for a ticker, defaulting to 'Unknown'."""
    return TICKER_INDUSTRY_MAP.get(ticker.upper(), DEFAULT_INDUSTRY)
